### PR TITLE
add new action: answerCards

### LINKED ISSUE #148: Feature Request: answerCard action
Currently API exposes operation `guiAnswerCard`. This operation depends on current GUI state.

In my opinion similar operation, but independent to GUI state, is missing.

Example request:

```
{
    "action": "answerCard",
    "version": 6,
    "params": {
        "ease": 1,
        "cardId": 1498938915662
    }
}
```

### PR DESCRIPTION
**Pull request by antistic**
fixes #148

might address #386

thanks for the plugin :)

### CODE REVIEW

**Comment by FooSoft** [comment]
Thanks for the PR! Could you make it so that instead of having two parallel lists, the API instead takes a single list of objects that have a cardId and answer value? That will be more robust than trying to make sure that the lists are always have the same # of elements and are lining up correctly.

**Comment by antistic** [comment]
Sure, I initially did it that way to match with `setEaseFactors` but you're right a list of objects makes it easier.

**Comment by antistic** [comment]
i went with the last one but called it "ease" since that matches the anki code, though i'm happy to change it to "button" or something else

**Comment by FooSoft** [comment]
Looks good to me!

**Pull request merged**
