### PR TITLE
Extend guiAddCards so that it's possible to preset notes

### PR DESCRIPTION
**Pull request by hgiesel**
This would add much more functionality to the guiAddCards endpoint. It basically gives it all the options that addNote currently has (except the sound parts, but I'm sure it wouldn't be hard to add that as well).
For more information, also see #10

I've also added something a bit more out there:
Enabling the option 'closeAfterAdding', you can create an `AddCards` window which closes as soon as you create the note. I find it very helpful, if you technically have all the card information you want, but you want to give the user the ability to review the information before commiting it to the collection.
Makes it also more reasonable to open multiple windows, which would all close, as you accept/edit the cards, instead of remaining on the screen.

### CODE REVIEW

**Comment by hgiesel** [comment]
I noticed two more things:
* Creating two "AddAndClose" dialogs, closing one, and exiting Anki crashes. The reason is that every "AddAndClose" dialog signs up on the windowing system with the same name.
* You cannot simply open a dialogue with just "option", but not "modelName", or "deckName", but I see that more as a feature than a bug

**Comment by hgiesel** [comment]
Ok thanks for the feedback.
Another thing I want to mention: even if calling `guiAddCards` with a note parameter will recreate the window, I will leave the call without the `note` parameter to just _activate the window_, keeping backwards compatibility in that sense. Basically there'll be three distinct use cases for the `guiAddCards` action: Activating the window, opening/reopening the `AddCards` dialog, opening `AddCardsAndClose` dialog. I'll try to reflect that in the README as well.

**Comment by hgiesel** [comment]
Okay I fixed all the bugs, created unit tests, and updated the README.
The only small caveat: On Anki 2.0, it won't recognize the new content of the fields, until you click on them once. But I made sure, the closeAfterAdding option doesn't close the window until you actually added something...

**Comment by hgiesel** [comment]
I have to admit I found another bug concerning model ids...
When I have the time I'll try and fix it...

**Comment by hgiesel** [comment]
OK, I fixed all bugs that were still present. However the caveat on Anki 2.0 previously mentioned still stands. Besides that, everything works as intended.

**Comment by FooSoft** [comment]
Looks good, but what is `meta.json`?

**Comment by hgiesel** [comment]
Oops, the file must have been created by Anki without me noticing. I removed it.

**Comment by FooSoft** [comment]
Awesome, thanks for the code!

**Pull request merged**
