### PR TITLE
Fix API params handler

### PR DESCRIPTION
**Pull request by vchagaev**
There was a problem with adding notes

### CODE REVIEW

**Comment by FooSoft** [comment]
Looks good, thank you for your contribution!

**Comment by FooSoft** [comment]
Even though upon initial glance this looked fine, this actually immediately breaks Yomichan. All of the functions expect parameters with the same names as those in the `params` object. Your change just passes the objects around directly, breaking most `canAddNotes` and probably almost everything else.

I'm reverting this change for now.

**Comment by vchagaev** [comment]
Oh, sorry!
I think in this case we should fix readme because it contains a wrong example for 'addNote'.

**Comment by FooSoft** [comment]
Are you referring to the sample JSON blob for `addNote` or the sample JavaScript function for using the API? Both look OK to me, but it is possible I'm missing something.

**Comment by vchagaev** [comment]
This doesn't work for me. It returns null.

`curl localhost:8765 -X POST -d '{"action": "addNote", "params": {"deckName": "English", "modelName": "two", "fields": {"Front": "TestFront", "Back": "TestBack"}}}'`

**Comment by FooSoft** [comment]
Looks like the docs were wrong, sorry about that, I will update them now. The command below will work:
```
curl localhost:8765 -X POST -d '{"action": "addNote", "params": {"note": {"deckName": "English", "modelName": "two", "fields": {"Front": "TestFront", "Back": "TestBack"}}}}'
```

**Comment by FooSoft** [comment]
Docs have been updated. Please open an issue if you are still running into problems :+1:

**Pull request merged**
