### PR TITLE
misc + new methods: cardsInfo now also returns the fields with stripped media + createFilteredDeck + runConsoleCmd + setSpecificValueOfCard + bury / unbury 

### PR DESCRIPTION
**Pull request by thiswillbeyourgithub**

### CODE REVIEW

**Comment by thiswillbeyourgithub** [comment]
Regarding the latest commit:e4f893b I was thinking of maybe, if "always" is set, generating a random number and if greater than a threshold then warn the user anyway. This would avoid having user letting the option on and forgetting about it. Let me know if you want me to add this.

**Comment by thiswillbeyourgithub** [comment]
Hi, [the project I created](https://github.com/thiswillbeyourgithub/AnnA_Anki_neuronal_Appendix) that needed some features from Anki-Connect is now finished. It would be great if you could review my changes so that I can begin to publicly talk about it.

Currently I am the only on to be able to use my script because my modification to anki-connect is not yet centralized here :)

Let me know if I can be of any help!

**Comment by thiswillbeyourgithub** [comment]
up :)

**Comment by thiswillbeyourgithub** [comment]
Hi, with no answer from you I'm more and more thinking about forking anki connect to make a distinct anki addon for my specific use.

Is that okay for you? (I would of course be very clear that it's just a minimalized fork and pay credits when due :) )

**Comment by FooSoft** [comment]
You are certainly more than welcome to fork. As it stands, the PR is pretty large and there are many issues with it. Unfortunately going over the design and naming of individual APIs, checking coding style, and validating that everything works takes a solid block of time which I never seem to have. This is why this has been getting punted for a while.

Some top level issues:
* No unit tests
* Style inconsistency even within this change alone (for example single quotes vs double quotes)
* Weird parameterization of actions like `createFilteredDeck` and `runConsoleCmd` (what good does the token do)
* Still not happy with security implications of `runConsoleCmd`... you can't even see what command is about to be executed.

If you break this up into smaller bits we can go over them individually.

**Comment by TobiasWehrum** [comment]
@thiswillbeyourgithub, do you think it might be possible to resubmit `setSpecificValueOfCard`? It's the only way I found to set the due date of a card (see also https://github.com/FooSoft/anki-connect/issues/122).

**Comment by thiswillbeyourgithub** [comment]
done

**Pull request closed without merging**
