### PR TITLE
Fix #392 with version check for Anki and Qt

### PR DESCRIPTION
**Pull request by mikkkee**
Hi, 

Some tests are failing due to #392 , there are two kinds of errors

1. `aqt.import_export` doesn't exist, it turns out this is only added in Anki 2.1.52. See #1743 in https://github.com/ankitects/anki/compare/2.1.51...2.1.52 
2. `Qt.WindowStaysOnTopHint` doesn't exist, it turns out it's of a different name in Qt6. 

This pull request is to handle both and update doc to make it clear `guiImportFile` is only supported >=2.1.52

Thanks!

### CODE REVIEW

**Comment by mikkkee** [comment]
Oh looks I need to add a button click after bringing up the import window to avoid timeout

**Comment by mikkkee** [comment]
Tests are good now 😄

**Comment by FooSoft** [comment]
Nice, thanks for fixing up the back compat!

**Comment by mikkkee** [comment]
This test fails, but it looks not related to this change.

https://github.com/FooSoft/anki-connect/actions/runs/5495042567/jobs/10014182696

**Pull request merged**
