### PR TITLE
Produce a better error in case of malformed JSON

### PR DESCRIPTION
**Pull request by oakkitten**
This solves the same issue that #317 solves, albeit slightly differently. I was hoping that the author would reopen the issue... There's a few differences;

* If origin is not allowed, 403 is returned in case of malformed JSON, and
* In case of JSON error, error string is returned to user.

I also noticed this bit: `params['params'] = params.get('params', {})`. It's a tad dangerous since this part of code can be run when not allowed, and `params` can be present but not be a dictionary. In this case the plugin would “crash”, and while this only amounts to showing a window with an error, it can be theoretically triggered by a malicious website, so I opted for verifying request schema. (Anki comes with `jsonschema` which is used to verify addon configurations.) This is not ideal, but I wanted to touch as little code as possible.

I added a few tests that test behavior around the change.

@nvlled Could you please look at this and tell if I did something stupid? 😬

### CODE REVIEW

**Comment by FooSoft** [comment]
Looks great to me :)

**Comment by oakkitten** [comment]
I really wish @nvlled said something, it now feels like I stole their PR :<

**Comment by nvlled** [comment]
Sorry, I couldn't find the time to give a thorough review. But I do one nit: explicity initialize params outside of the try block. Something like:
```python
params = {}
try:
    params = json.loads(req.body.decode('utf-8'))
```

The bug I encountered was specifically cause by an uninitialized params variable. It would be nice to prevent this from happening when changes are made in the future.

**Comment by oakkitten** [comment]
Ah, that should be solved in this PR! In the `except` part of the of the block, if continuing, the `params` variable is set. I suppose one could also set it before like in your example. It's just that I use PyCharm and I'm accustomed to it warning me if I forget to set a variable in one of the execution branches.

https://github.com/FooSoft/anki-connect/blob/9c3310a8b6202f93ed42ec13461566659b1e2036/plugin/web.py#L179-L192

I'd still appreciate the review! Anyway, I guess I better make this not a draft since, well, the button says “Ready for review” :p

**Comment by FooSoft** [comment]
Looks good to me!

**Comment by oakkitten** [comment]
P.S. the tests are failing now due to protobuf update (packages anki/aqt don't pin dependencies), I'll have a fix shortly

**Comment by FooSoft** [comment]
Thanks!

**Pull request merged**
