### PR TITLE
Clarify the documentation for people using something other than Javascript

### PR DESCRIPTION
**Pull request by davidshepherd7**

### CODE REVIEW

**Comment by FooSoft** [comment]
Looks good, thank you for the PR!

**Comment by davidshepherd7** [comment]
Thanks for making this!

Just in case you're interested I'm using anki-connect to make a cli-and-text-files interface for creating Anki cards so that I can use a proper editor (emacs) to write them. I've got a very basic version working: https://github.com/davidshepherd7/ankicli

**Comment by FooSoft** [comment]
Hey, that's pretty neat! 

But wait, you mentioned that you want to use a proper editor, but I didn't see a vim plugin anywhere in the repo :fire: :fire: fire:

Looking good!

**Comment by davidshepherd7** [comment]
Ohhhh shots fired :fire: :gun:

But in seriousness, it's editor-agnostic (at least so far) so it should be easy to integrate with vim as well. Unfortunately not everyone in the world uses emacs!

**Pull request merged**
